<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>

    <FileVersion>1.2.0</FileVersion>


    <DebugType>none</DebugType>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

    <ItemGroup>
    <EmbeddedResource Include="Resources/kodestudio" />
    </ItemGroup>
    
</Project>